[package]
name = "site-compiler"
version = "0.1.0"
edition = "2021"

[dependencies]
kuchiki = "0.8"
sha2 = "0.10"
notify = "6.1"
walkdir = "2.4"
chrono = "0.4"
regex = "1"

[profile.release]
opt-level = "s"
lto = "fat"
codegen-units = 1
panic = "abort"
strip = "symbols"
